-- Global Power Plant Legacy Database
-- Simulates a legacy enterprise energy management system with
-- abbreviated column names, code values, and ugly conventions.

-- Country reference table
CREATE TABLE CNTRY_REF (
    CNTRY_CD     VARCHAR(3) NOT NULL,
    CNTRY_NM     VARCHAR(80) NOT NULL,
    RGN_CD       VARCHAR(4),
    ACTV_FLG     CHAR(1) NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_CNTRY_REF PRIMARY KEY (CNTRY_CD),
    CONSTRAINT CHK_CNTRY_ACTV CHECK (ACTV_FLG IN ('Y', 'N'))
);

-- Fuel type reference table
CREATE TABLE FUEL_TYPE_REF (
    FUEL_CD      VARCHAR(4) NOT NULL,
    FUEL_DESC    VARCHAR(40) NOT NULL,
    FUEL_CAT_CD  VARCHAR(2) NOT NULL,
    CONSTRAINT PK_FUEL_TYPE_REF PRIMARY KEY (FUEL_CD),
    CONSTRAINT CHK_FUEL_CAT CHECK (FUEL_CAT_CD IN ('RE', 'FF', 'NR', 'OT'))
);

-- Power plant core table
CREATE TABLE PWR_PLT (
    PLT_ID       SERIAL NOT NULL,
    PLT_EXT_CD   VARCHAR(20) NOT NULL,
    PLT_NM       VARCHAR(200) NOT NULL,
    CNTRY_CD     VARCHAR(3) NOT NULL,
    CAP_KW       INTEGER NOT NULL,
    LAT_DEG      INTEGER,
    LON_DEG      INTEGER,
    COMM_DT      VARCHAR(8),
    OWNR_NM      VARCHAR(200),
    STAT_CD      VARCHAR(2) NOT NULL DEFAULT 'OP',
    WEPP_CD      VARCHAR(20),
    CAP_YR       INTEGER,
    SRC_NM       VARCHAR(100),
    SRC_URL      VARCHAR(500),
    GEO_SRC_NM   VARCHAR(100),
    CRT_TS       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_TS       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PWR_PLT PRIMARY KEY (PLT_ID),
    CONSTRAINT FK_PWR_PLT_CNTRY FOREIGN KEY (CNTRY_CD) REFERENCES CNTRY_REF(CNTRY_CD),
    CONSTRAINT UQ_PWR_PLT_EXT UNIQUE (PLT_EXT_CD),
    CONSTRAINT CHK_PLT_STAT CHECK (STAT_CD IN ('OP', 'CL', 'PL', 'UC'))
);

-- Plant fuel assignments (many-to-many, with rank)
CREATE TABLE PLT_FUEL_ASGN (
    ASGN_ID      SERIAL NOT NULL,
    PLT_ID       INTEGER NOT NULL,
    FUEL_CD      VARCHAR(4) NOT NULL,
    FUEL_RNK     INTEGER NOT NULL,
    CONSTRAINT PK_PLT_FUEL_ASGN PRIMARY KEY (ASGN_ID),
    CONSTRAINT FK_PFA_PLT FOREIGN KEY (PLT_ID) REFERENCES PWR_PLT(PLT_ID),
    CONSTRAINT FK_PFA_FUEL FOREIGN KEY (FUEL_CD) REFERENCES FUEL_TYPE_REF(FUEL_CD),
    CONSTRAINT UQ_PFA_PLT_RNK UNIQUE (PLT_ID, FUEL_RNK),
    CONSTRAINT CHK_FUEL_RNK CHECK (FUEL_RNK BETWEEN 1 AND 4)
);

-- Annual generation data
CREATE TABLE GEN_DATA (
    GEN_ID       SERIAL NOT NULL,
    PLT_ID       INTEGER NOT NULL,
    RPT_YR       INTEGER NOT NULL,
    ACT_GEN_MWH  INTEGER,
    EST_GEN_MWH  INTEGER,
    EST_MTHD_CD  VARCHAR(20),
    DATA_SRC_NM  VARCHAR(100),
    CONSTRAINT PK_GEN_DATA PRIMARY KEY (GEN_ID),
    CONSTRAINT FK_GEN_PLT FOREIGN KEY (PLT_ID) REFERENCES PWR_PLT(PLT_ID),
    CONSTRAINT UQ_GEN_PLT_YR UNIQUE (PLT_ID, RPT_YR)
);

-- Indexes for common queries
CREATE INDEX IDX_PWR_PLT_CNTRY ON PWR_PLT(CNTRY_CD);
CREATE INDEX IDX_PWR_PLT_STAT ON PWR_PLT(STAT_CD);
CREATE INDEX IDX_PFA_PLT ON PLT_FUEL_ASGN(PLT_ID);
CREATE INDEX IDX_PFA_FUEL ON PLT_FUEL_ASGN(FUEL_CD);
CREATE INDEX IDX_GEN_PLT ON GEN_DATA(PLT_ID);
CREATE INDEX IDX_GEN_YR ON GEN_DATA(RPT_YR);

-- CDC: enable logical replication
ALTER TABLE CNTRY_REF REPLICA IDENTITY FULL;
ALTER TABLE FUEL_TYPE_REF REPLICA IDENTITY FULL;
ALTER TABLE PWR_PLT REPLICA IDENTITY FULL;
ALTER TABLE PLT_FUEL_ASGN REPLICA IDENTITY FULL;
ALTER TABLE GEN_DATA REPLICA IDENTITY FULL;

CREATE PUBLICATION meshql_pub FOR TABLE CNTRY_REF, FUEL_TYPE_REF, PWR_PLT, PLT_FUEL_ASGN, GEN_DATA;
