-- Springfield Electric Cooperative Legacy Database
-- "If it ain't broke, don't fix it" — Database Administrator, 1998

-- ============================================================
-- CUSTOMER ACCOUNTS
-- ============================================================
CREATE TABLE CUST_ACCT (
    ACCT_ID         SERIAL PRIMARY KEY,
    ACCT_NUM        VARCHAR(12) NOT NULL UNIQUE,
    CUST_NM_FIRST   VARCHAR(30) NOT NULL,
    CUST_NM_LAST    VARCHAR(30) NOT NULL,
    ADDR_LN1        VARCHAR(60),
    ADDR_LN2        VARCHAR(60),
    ADDR_CITY       VARCHAR(30),
    ADDR_ST         VARCHAR(2),
    ADDR_ZIP        VARCHAR(10),
    PHONE_NUM       VARCHAR(15),
    EMAIL_ADDR      VARCHAR(60),
    RT_CD           VARCHAR(3) NOT NULL,       -- RES, COM, IND
    SVC_TYPE        VARCHAR(1) NOT NULL,       -- E=Electric, G=Gas, B=Both
    STAT_CD         VARCHAR(1) NOT NULL,       -- A=Active, S=Suspended, C=Closed
    CONN_DT         VARCHAR(8) NOT NULL,       -- YYYYMMDD
    DISC_DT         VARCHAR(8),               -- YYYYMMDD or NULL
    BUDGET_FLG      VARCHAR(1) DEFAULT 'N',   -- Y/N
    PAPERLESS_FLG   VARCHAR(1) DEFAULT 'N'    -- Y/N
);

ALTER TABLE CUST_ACCT REPLICA IDENTITY FULL;

-- ============================================================
-- METER READINGS
-- ============================================================
CREATE TABLE MTR_RDNG (
    RDNG_ID         SERIAL PRIMARY KEY,
    ACCT_ID         INTEGER NOT NULL REFERENCES CUST_ACCT(ACCT_ID),
    MTR_NUM         VARCHAR(12) NOT NULL,
    RDNG_DT         VARCHAR(8) NOT NULL,       -- YYYYMMDD
    RDNG_VAL        INTEGER NOT NULL,          -- kWh cumulative
    PREV_RDNG_VAL   INTEGER,                   -- Previous reading
    RDNG_TYPE       VARCHAR(1) NOT NULL,       -- A=Actual, E=Estimated, C=Customer
    EST_FLG         VARCHAR(1) DEFAULT 'N',    -- Y/N
    BILLED_FLG      VARCHAR(1) DEFAULT 'N'     -- Y/N
);

ALTER TABLE MTR_RDNG REPLICA IDENTITY FULL;

-- ============================================================
-- BILL HEADERS
-- ============================================================
CREATE TABLE BILL_HDR (
    BILL_ID         SERIAL PRIMARY KEY,
    ACCT_ID         INTEGER NOT NULL REFERENCES CUST_ACCT(ACCT_ID),
    BILL_DT         VARCHAR(8) NOT NULL,       -- YYYYMMDD
    DUE_DT          VARCHAR(8) NOT NULL,       -- YYYYMMDD
    BILL_PRD_FROM   VARCHAR(8) NOT NULL,       -- YYYYMMDD
    BILL_PRD_TO     VARCHAR(8) NOT NULL,       -- YYYYMMDD
    TOT_AMT         INTEGER NOT NULL,          -- Amount in CENTS
    KWH_USED        INTEGER NOT NULL,
    STAT_CD         VARCHAR(1) NOT NULL,       -- O=Open, P=Paid, D=Delinquent, X=Cancelled
    LATE_FLG        VARCHAR(1) DEFAULT 'N'     -- Y/N
);

ALTER TABLE BILL_HDR REPLICA IDENTITY FULL;

-- ============================================================
-- PAYMENT HISTORY
-- ============================================================
CREATE TABLE PYMT_HIST (
    PYMT_ID         SERIAL PRIMARY KEY,
    ACCT_ID         INTEGER NOT NULL REFERENCES CUST_ACCT(ACCT_ID),
    BILL_ID         INTEGER REFERENCES BILL_HDR(BILL_ID),
    PYMT_DT         VARCHAR(8) NOT NULL,       -- YYYYMMDD
    PYMT_AMT        INTEGER NOT NULL,          -- Amount in CENTS
    PYMT_MTHD       VARCHAR(1) NOT NULL,       -- W=Web, E=Electronic, K=Check, C=Cash, P=Phone
    CONF_NUM        VARCHAR(20),
    STAT_CD         VARCHAR(1) DEFAULT 'S'     -- S=Success, F=Failed, R=Refunded
);

ALTER TABLE PYMT_HIST REPLICA IDENTITY FULL;

-- ============================================================
-- SEED DATA
-- ============================================================

-- Customer 1: Margaret Henderson — Residential, Active since 1998
INSERT INTO CUST_ACCT (ACCT_NUM, CUST_NM_FIRST, CUST_NM_LAST, ADDR_LN1, ADDR_CITY, ADDR_ST, ADDR_ZIP, PHONE_NUM, EMAIL_ADDR, RT_CD, SVC_TYPE, STAT_CD, CONN_DT, BUDGET_FLG, PAPERLESS_FLG)
VALUES ('100100-00001', 'MARGARET', 'HENDERSON', '742 EVERGREEN TERRACE', 'SPRINGFIELD', 'IL', '62704', '217-555-0142', 'MHENDERSON@EMAIL.COM', 'RES', 'E', 'A', '19980315', 'Y', 'N');

-- Customer 2: Kenji Nakamura — Commercial, Active since 2005
INSERT INTO CUST_ACCT (ACCT_NUM, CUST_NM_FIRST, CUST_NM_LAST, ADDR_LN1, ADDR_LN2, ADDR_CITY, ADDR_ST, ADDR_ZIP, PHONE_NUM, EMAIL_ADDR, RT_CD, SVC_TYPE, STAT_CD, CONN_DT, PAPERLESS_FLG)
VALUES ('200200-00002', 'KENJI', 'NAKAMURA', '1200 INDUSTRIAL PKWY', 'SUITE 300', 'SPRINGFIELD', 'IL', '62707', '217-555-0298', 'KNAKAMURA@NAKAMURAFOODS.COM', 'COM', 'B', 'A', '20050601', 'Y');

-- Customer 3: Siobhan O'Connell — Residential, Suspended
INSERT INTO CUST_ACCT (ACCT_NUM, CUST_NM_FIRST, CUST_NM_LAST, ADDR_LN1, ADDR_CITY, ADDR_ST, ADDR_ZIP, PHONE_NUM, RT_CD, SVC_TYPE, STAT_CD, CONN_DT)
VALUES ('100100-00003', 'SIOBHAN', 'OCONNELL', '88 OAK STREET', 'SPRINGFIELD', 'IL', '62702', '217-555-0177', 'RES', 'E', 'S', '20120910');

-- Customer 4: James Whitfield — Industrial, Active since 2001
INSERT INTO CUST_ACCT (ACCT_NUM, CUST_NM_FIRST, CUST_NM_LAST, ADDR_LN1, ADDR_CITY, ADDR_ST, ADDR_ZIP, PHONE_NUM, EMAIL_ADDR, RT_CD, SVC_TYPE, STAT_CD, CONN_DT, PAPERLESS_FLG)
VALUES ('300300-00004', 'JAMES', 'WHITFIELD', '5000 RIVER ROAD', 'SPRINGFIELD', 'IL', '62711', '217-555-0455', 'JWHITFIELD@WHITFIELDMFG.COM', 'IND', 'E', 'A', '20010220', 'Y');

-- ============================================================
-- METER READINGS
-- ============================================================

-- Henderson readings (meter M-10042)
INSERT INTO MTR_RDNG (ACCT_ID, MTR_NUM, RDNG_DT, RDNG_VAL, PREV_RDNG_VAL, RDNG_TYPE, EST_FLG, BILLED_FLG)
VALUES (1, 'M-10042', '20250601', 42150, 41200, 'A', 'N', 'Y');
INSERT INTO MTR_RDNG (ACCT_ID, MTR_NUM, RDNG_DT, RDNG_VAL, PREV_RDNG_VAL, RDNG_TYPE, EST_FLG, BILLED_FLG)
VALUES (1, 'M-10042', '20250701', 43280, 42150, 'A', 'N', 'Y');
INSERT INTO MTR_RDNG (ACCT_ID, MTR_NUM, RDNG_DT, RDNG_VAL, PREV_RDNG_VAL, RDNG_TYPE, EST_FLG, BILLED_FLG)
VALUES (1, 'M-10042', '20250801', 45230, 43280, 'E', 'Y', 'Y');
INSERT INTO MTR_RDNG (ACCT_ID, MTR_NUM, RDNG_DT, RDNG_VAL, PREV_RDNG_VAL, RDNG_TYPE, EST_FLG, BILLED_FLG)
VALUES (1, 'M-10042', '20250901', 46100, 45230, 'A', 'N', 'N');

-- Nakamura readings (meter M-20087)
INSERT INTO MTR_RDNG (ACCT_ID, MTR_NUM, RDNG_DT, RDNG_VAL, PREV_RDNG_VAL, RDNG_TYPE, EST_FLG, BILLED_FLG)
VALUES (2, 'M-20087', '20250601', 128400, 124200, 'A', 'N', 'Y');
INSERT INTO MTR_RDNG (ACCT_ID, MTR_NUM, RDNG_DT, RDNG_VAL, PREV_RDNG_VAL, RDNG_TYPE, EST_FLG, BILLED_FLG)
VALUES (2, 'M-20087', '20250701', 133100, 128400, 'A', 'N', 'Y');
INSERT INTO MTR_RDNG (ACCT_ID, MTR_NUM, RDNG_DT, RDNG_VAL, PREV_RDNG_VAL, RDNG_TYPE, EST_FLG, BILLED_FLG)
VALUES (2, 'M-20087', '20250801', 137500, 133100, 'A', 'N', 'Y');
INSERT INTO MTR_RDNG (ACCT_ID, MTR_NUM, RDNG_DT, RDNG_VAL, PREV_RDNG_VAL, RDNG_TYPE, EST_FLG, BILLED_FLG)
VALUES (2, 'M-20087', '20250901', 141200, 137500, 'A', 'N', 'N');

-- O'Connell readings (meter M-10098)
INSERT INTO MTR_RDNG (ACCT_ID, MTR_NUM, RDNG_DT, RDNG_VAL, PREV_RDNG_VAL, RDNG_TYPE, EST_FLG, BILLED_FLG)
VALUES (3, 'M-10098', '20250601', 31200, 30400, 'A', 'N', 'Y');
INSERT INTO MTR_RDNG (ACCT_ID, MTR_NUM, RDNG_DT, RDNG_VAL, PREV_RDNG_VAL, RDNG_TYPE, EST_FLG, BILLED_FLG)
VALUES (3, 'M-10098', '20250701', 31900, 31200, 'E', 'Y', 'Y');

-- Whitfield readings (meter M-30015)
INSERT INTO MTR_RDNG (ACCT_ID, MTR_NUM, RDNG_DT, RDNG_VAL, PREV_RDNG_VAL, RDNG_TYPE, EST_FLG, BILLED_FLG)
VALUES (4, 'M-30015', '20250601', 892000, 878000, 'A', 'N', 'Y');
INSERT INTO MTR_RDNG (ACCT_ID, MTR_NUM, RDNG_DT, RDNG_VAL, PREV_RDNG_VAL, RDNG_TYPE, EST_FLG, BILLED_FLG)
VALUES (4, 'M-30015', '20250701', 906500, 892000, 'A', 'N', 'Y');
INSERT INTO MTR_RDNG (ACCT_ID, MTR_NUM, RDNG_DT, RDNG_VAL, PREV_RDNG_VAL, RDNG_TYPE, EST_FLG, BILLED_FLG)
VALUES (4, 'M-30015', '20250801', 921800, 906500, 'A', 'N', 'Y');
INSERT INTO MTR_RDNG (ACCT_ID, MTR_NUM, RDNG_DT, RDNG_VAL, PREV_RDNG_VAL, RDNG_TYPE, EST_FLG, BILLED_FLG)
VALUES (4, 'M-30015', '20250901', 935400, 921800, 'A', 'N', 'N');

-- ============================================================
-- BILLS
-- ============================================================

-- Henderson bills
INSERT INTO BILL_HDR (ACCT_ID, BILL_DT, DUE_DT, BILL_PRD_FROM, BILL_PRD_TO, TOT_AMT, KWH_USED, STAT_CD, LATE_FLG)
VALUES (1, '20250615', '20250715', '20250601', '20250630', 9840, 950, 'P', 'N');
INSERT INTO BILL_HDR (ACCT_ID, BILL_DT, DUE_DT, BILL_PRD_FROM, BILL_PRD_TO, TOT_AMT, KWH_USED, STAT_CD, LATE_FLG)
VALUES (1, '20250715', '20250815', '20250701', '20250731', 11720, 1130, 'P', 'N');
INSERT INTO BILL_HDR (ACCT_ID, BILL_DT, DUE_DT, BILL_PRD_FROM, BILL_PRD_TO, TOT_AMT, KWH_USED, STAT_CD, LATE_FLG)
VALUES (1, '20250815', '20250915', '20250801', '20250831', 20220, 1950, 'O', 'N');

-- Nakamura bills
INSERT INTO BILL_HDR (ACCT_ID, BILL_DT, DUE_DT, BILL_PRD_FROM, BILL_PRD_TO, TOT_AMT, KWH_USED, STAT_CD, LATE_FLG)
VALUES (2, '20250615', '20250715', '20250601', '20250630', 42000, 4200, 'P', 'N');
INSERT INTO BILL_HDR (ACCT_ID, BILL_DT, DUE_DT, BILL_PRD_FROM, BILL_PRD_TO, TOT_AMT, KWH_USED, STAT_CD, LATE_FLG)
VALUES (2, '20250715', '20250815', '20250701', '20250731', 47000, 4700, 'P', 'N');
INSERT INTO BILL_HDR (ACCT_ID, BILL_DT, DUE_DT, BILL_PRD_FROM, BILL_PRD_TO, TOT_AMT, KWH_USED, STAT_CD, LATE_FLG)
VALUES (2, '20250815', '20250915', '20250801', '20250831', 44000, 4400, 'O', 'N');

-- O'Connell bills
INSERT INTO BILL_HDR (ACCT_ID, BILL_DT, DUE_DT, BILL_PRD_FROM, BILL_PRD_TO, TOT_AMT, KWH_USED, STAT_CD, LATE_FLG)
VALUES (3, '20250615', '20250715', '20250601', '20250630', 8300, 800, 'D', 'Y');
INSERT INTO BILL_HDR (ACCT_ID, BILL_DT, DUE_DT, BILL_PRD_FROM, BILL_PRD_TO, TOT_AMT, KWH_USED, STAT_CD, LATE_FLG)
VALUES (3, '20250715', '20250815', '20250701', '20250731', 7250, 700, 'D', 'Y');

-- Whitfield bills
INSERT INTO BILL_HDR (ACCT_ID, BILL_DT, DUE_DT, BILL_PRD_FROM, BILL_PRD_TO, TOT_AMT, KWH_USED, STAT_CD, LATE_FLG)
VALUES (4, '20250615', '20250715', '20250601', '20250630', 98000, 14000, 'P', 'N');
INSERT INTO BILL_HDR (ACCT_ID, BILL_DT, DUE_DT, BILL_PRD_FROM, BILL_PRD_TO, TOT_AMT, KWH_USED, STAT_CD, LATE_FLG)
VALUES (4, '20250815', '20250915', '20250801', '20250831', 106200, 15300, 'O', 'N');

-- ============================================================
-- PAYMENTS
-- ============================================================

-- Henderson payments
INSERT INTO PYMT_HIST (ACCT_ID, BILL_ID, PYMT_DT, PYMT_AMT, PYMT_MTHD, CONF_NUM, STAT_CD)
VALUES (1, 1, '20250702', 9840, 'W', 'WEB-20250702-001', 'S');
INSERT INTO PYMT_HIST (ACCT_ID, BILL_ID, PYMT_DT, PYMT_AMT, PYMT_MTHD, CONF_NUM, STAT_CD)
VALUES (1, 2, '20250810', 11720, 'W', 'WEB-20250810-002', 'S');

-- Nakamura payments
INSERT INTO PYMT_HIST (ACCT_ID, BILL_ID, PYMT_DT, PYMT_AMT, PYMT_MTHD, CONF_NUM, STAT_CD)
VALUES (2, 4, '20250620', 42000, 'E', 'ACH-20250620-001', 'S');
INSERT INTO PYMT_HIST (ACCT_ID, BILL_ID, PYMT_DT, PYMT_AMT, PYMT_MTHD, CONF_NUM, STAT_CD)
VALUES (2, 5, '20250725', 47000, 'E', 'ACH-20250725-002', 'S');

-- Whitfield payments
INSERT INTO PYMT_HIST (ACCT_ID, BILL_ID, PYMT_DT, PYMT_AMT, PYMT_MTHD, CONF_NUM, STAT_CD)
VALUES (4, 10, '20250630', 98000, 'K', 'CHK-004872', 'S');

-- O'Connell — no payments (delinquent)

-- ============================================================
-- PUBLICATION FOR DEBEZIUM CDC
-- ============================================================
CREATE PUBLICATION legacy_pub FOR ALL TABLES;
